"""read_context_ref

Revision ID: 0002_read_context_ref
Revises: 0001_initial
Create Date: 2026-06-26 08:18:24.587237

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0002_read_context_ref"
down_revision: Union[str, Sequence[str], None] = "0001_initial"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fervis_conversation", sa.Column("read_context_ref", sa.JSON(), nullable=False)
    )
    op.add_column(
        "fervis_run_work_item", sa.Column("read_context_ref", sa.JSON(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fervis_run_work_item", "read_context_ref")
    op.drop_column("fervis_conversation", "read_context_ref")
    # ### end Alembic commands ###
