# Generated by Django 5.2 on 2026-06-26 08:18

import fervis.run_work.queue.django.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fervis_jobs", "0003_remove_max_turns"),
    ]

    operations = [
        migrations.AddField(
            model_name="runworkitem",
            name="read_context_ref",
            field=models.JSONField(
                default=fervis.run_work.queue.django.models.default_read_context_ref
            ),
        ),
    ]
