"""Runtime event payload constants used for observability projections."""

from __future__ import annotations


class EventType:
    MODEL_TURN_COMPLETED = "model_turn.completed"
    MODEL_TURN_FAILED = "model_turn.failed"
    FACT_PLAN_EXECUTION = "fact_plan_execution"
    RESPONSE_RENDERING = "response_rendering"


class EventPayloadKey:
    RUN_ID = "runId"
    TURN = "turn"
    PURPOSE = "purpose"
    PROVIDER = "provider"
    MODEL_KEY = "modelKey"
    PROVIDER_MODEL = "providerModel"
    PROVIDER_REQUEST_ID = "providerRequestId"
    MODEL_OUTPUT = "modelOutput"
    ARGUMENTS = "arguments"
    PARSED_ARGUMENTS = "parsedArguments"
    DERIVED_ARGUMENTS = "derivedArguments"
    SELECTED_TOOL_NAME = "selectedToolName"
    TOOL_RESULT = "toolResult"
    MESSAGES = "messages"
    ANSWER_SOURCE = "answerSource"
    ERROR_CODE = "errorCode"
    ERROR_CLASS = "errorClass"
    ERROR_CONTEXT = "errorContext"
    FACT_ADDRESSES = "factAddresses"
    FACT_OUTCOME_ADDRESSES = "factOutcomeAddresses"
    USAGE = "usage"
    PROMPT_CHARS = "promptChars"
    PROMPT_HASH = "promptHash"
    PROMPT_FRAME = "promptFrame"
    TOOL_SPEC_CHARS = "toolSpecChars"
    TOOL_SPEC_HASH = "toolSpecHash"
    SCHEMA_CHARS = "schemaChars"
    SCHEMA_HASH = "schemaHash"
    RAW_PROMPT = "rawPrompt"
    RAW_SYSTEM_PROMPT = "rawSystemPrompt"
    RAW_TOOL_SPECS = "rawToolSpecs"
    RAW_SCHEMA = "rawSchema"
    KIND = "kind"
    ROW_COUNT = "rowCount"
    RELATION_COUNT = "relationCount"
    PROOF_REFS = "proofRefs"


class ToolResultKey:
    OK = "ok"
    TOOL = "tool"
    STEP_ID = "stepId"
    RESULT = "result"
    ERROR = "error"
    ERROR_CODE = "errorCode"
    DURATION_MS = "durationMs"
    QUERY = "query"
    RESULTS = "results"
    ENDPOINT_NAME = "endpointName"
    RESPONSE_STATUS = "responseStatus"
    RESPONSE_BODY = "responseBody"
    REQUEST_URL = "requestUrl"
    REQUEST_PARAMS = "requestParams"
    PAGE_COUNT = "pageCount"
    TRUNCATED = "truncated"
    EVIDENCE_STEP_IDS = "evidenceStepIds"
    IS_COMPLETE = "isComplete"
    STATUS = "status"
    START = "start"
    END = "end"
    START_DATE = "start_date"
    END_DATE = "end_date"
    TIMEZONE = "timezone"
    ANCHOR_PERIOD = "anchorPeriod"
