# Generated by Django 5.2.15 on 2026-07-10 01:01

import django.db.models.deletion
import fervis.lineage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fervis_answer',
            },
        ),
        migrations.CreateModel(
            name='AnswerProgram',
            fields=[
                ('program_id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('schema_revision', models.PositiveIntegerField()),
                ('canonical_json', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fervis_answer_program',
            },
        ),
        migrations.CreateModel(
            name='FactResult',
            fields=[
                ('fact_result_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('result_kind', models.CharField(choices=[('answered', 'answered'), ('needs_clarification', 'needs_clarification'), ('impossible', 'impossible'), ('no_data', 'no_data'), ('undefined', 'undefined')], max_length=64)),
                ('evidence_refs_json', models.JSONField(blank=True, default=list)),
                ('payload_schema', models.CharField(blank=True, default='', max_length=128)),
                ('payload_schema_rev', models.PositiveIntegerField(blank=True, null=True)),
                ('payload_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fervis_fact_result',
            },
        ),
        migrations.CreateModel(
            name='ModelCall',
            fields=[
                ('model_call_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('call_index', models.PositiveIntegerField()),
                ('provider', models.CharField(max_length=64)),
                ('model_key', models.CharField(max_length=128)),
                ('provider_request_id', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('succeeded', 'succeeded'), ('failed', 'failed')], max_length=32)),
                ('finish_reason', models.CharField(blank=True, default='', max_length=64)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('reasoning_effort', models.CharField(blank=True, default='', max_length=64)),
                ('reasoning_budget_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('max_output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('prompt_chars', models.PositiveIntegerField(default=0)),
                ('schema_chars', models.PositiveIntegerField(default=0)),
                ('tool_spec_chars', models.PositiveIntegerField(default=0)),
                ('submitted_payload_chars', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_output_chars', models.PositiveIntegerField(blank=True, null=True)),
                ('model_subcalls_json', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fervis_model_call',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversation_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=128)),
                ('read_context_ref', models.JSONField(default=fervis.lineage.models.default_conversation_read_context_ref)),
                ('origin_kind', models.CharField(choices=[('initial', 'initial'), ('fork', 'fork')], default='initial', max_length=32)),
                ('origin_ref', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forks', to='fervis_lineage.conversation')),
            ],
            options={
                'db_table': 'fervis_conversation',
            },
        ),
        migrations.CreateModel(
            name='ClarificationRequest',
            fields=[
                ('clarification_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('need', models.CharField(choices=[('target_reference', 'target_reference'), ('answer_metric', 'answer_metric'), ('comparison_baseline', 'comparison_baseline'), ('catalog_input', 'catalog_input'), ('question_interpretation', 'question_interpretation')], max_length=64)),
                ('reason', models.CharField(choices=[('unresolved_reference', 'unresolved_reference'), ('multiple_matching_entities', 'multiple_matching_entities'), ('unsupported_reference', 'unsupported_reference'), ('missing_answer_metric', 'missing_answer_metric'), ('missing_comparison_baseline', 'missing_comparison_baseline'), ('missing_required_value', 'missing_required_value'), ('catalog_requires_choice', 'catalog_requires_choice'), ('ambiguous_interpretation', 'ambiguous_interpretation')], max_length=64)),
                ('payload_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fact_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clarification_requests', to='fervis_lineage.factresult')),
            ],
            options={
                'db_table': 'fervis_clarification_request',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('conversation_sequence', models.PositiveIntegerField()),
                ('origin_message_ref', models.CharField(blank=True, default='', max_length=255)),
                ('original_question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='fervis_lineage.conversation')),
            ],
            options={
                'db_table': 'fervis_question',
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='forked_after_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversation_forks', to='fervis_lineage.question'),
        ),
        migrations.CreateModel(
            name='QuestionRun',
            fields=[
                ('run_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('run_number', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('model_assisted', 'model_assisted'), ('deterministic', 'deterministic')], max_length=32)),
                ('trigger_kind', models.CharField(choices=[('initial', 'initial'), ('clarification_response', 'clarification_response'), ('retry', 'retry'), ('rerun', 'rerun')], default='initial', max_length=32)),
                ('trigger_clarification_response_id', models.CharField(blank=True, default='', max_length=128)),
                ('adapter_ref', models.CharField(max_length=128)),
                ('runtime_version', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_runs', to='fervis_lineage.questionrun')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='fervis_lineage.question')),
            ],
            options={
                'db_table': 'fervis_question_run',
            },
        ),
        migrations.CreateModel(
            name='ProgramInvocation',
            fields=[
                ('invocation_id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('bindings_json', models.TextField()),
                ('patch_id', models.CharField(blank=True, max_length=80, null=True)),
                ('binding_patch_json', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invocations', to='fervis_lineage.answerprogram')),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='program_invocation', to='fervis_lineage.questionrun')),
            ],
            options={
                'db_table': 'fervis_program_invocation',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('binding_patch_json__isnull', True), ('patch_id__isnull', True)), models.Q(('binding_patch_json__isnull', False), ('patch_id__isnull', False)), _connector='OR'), name='fervis_program_invocation_patch_pair_ck')],
            },
        ),
        migrations.CreateModel(
            name='ProgramRevision',
            fields=[
                ('revision_id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('capability_id', models.CharField(max_length=128)),
                ('application_json', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_revisions', to='fervis_lineage.answerprogram')),
                ('revised_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_revisions', to='fervis_lineage.answerprogram')),
            ],
            options={
                'db_table': 'fervis_program_revision',
                'indexes': [models.Index(fields=['base_program'], name='fervis_program_rev_base_idx'), models.Index(fields=['revised_program'], name='fervis_program_rev_revised_idx')],
            },
        ),
        migrations.AddField(
            model_name='programinvocation',
            name='revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invocations', to='fervis_lineage.programrevision'),
        ),
        migrations.CreateModel(
            name='ModelCallUsage',
            fields=[
                ('usage_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('usage_kind', models.CharField(choices=[('input_tokens', 'input_tokens'), ('cached_input_tokens', 'cached_input_tokens'), ('output_tokens', 'output_tokens'), ('reasoning_tokens', 'reasoning_tokens'), ('thinking_tokens', 'thinking_tokens'), ('tool_tokens', 'tool_tokens')], max_length=64)),
                ('quantity', models.PositiveBigIntegerField()),
                ('unit', models.CharField(choices=[('tokens', 'tokens'), ('chars', 'chars'), ('calls', 'calls')], max_length=32)),
                ('provider_usage_key', models.CharField(max_length=128)),
                ('cost_micros', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=16)),
                ('price_basis_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_call', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_rows', to='fervis_lineage.modelcall')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_call_usages', to='fervis_lineage.questionrun')),
            ],
            options={
                'db_table': 'fervis_model_call_usage',
            },
        ),
        migrations.AddField(
            model_name='modelcall',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_calls', to='fervis_lineage.questionrun'),
        ),
        migrations.AddField(
            model_name='factresult',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fact_results', to='fervis_lineage.questionrun'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='forked_after_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversation_forks', to='fervis_lineage.questionrun'),
        ),
        migrations.CreateModel(
            name='ClarificationResponse',
            fields=[
                ('response_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('source_message_ref', models.CharField(blank=True, default='', max_length=255)),
                ('selected_option_id', models.CharField(blank=True, default='', max_length=128)),
                ('response_text', models.TextField(blank=True, default='')),
                ('evidence_ref', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clarification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='fervis_lineage.clarificationrequest')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clarification_responses', to='fervis_lineage.questionrun')),
            ],
            options={
                'db_table': 'fervis_clarification_response',
            },
        ),
        migrations.AddField(
            model_name='clarificationrequest',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clarification_requests', to='fervis_lineage.questionrun'),
        ),
        migrations.CreateModel(
            name='CatalogEndpoint',
            fields=[
                ('catalog_endpoint_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('catalog_endpoint_key', models.CharField(max_length=128)),
                ('endpoint_name', models.CharField(db_index=True, max_length=128)),
                ('framework_kind', models.CharField(max_length=64)),
                ('source_namespace_kind', models.CharField(max_length=64)),
                ('source_namespace_path_json', models.JSONField(blank=True, default=list)),
                ('route_method', models.CharField(max_length=16)),
                ('route_path_template', models.CharField(max_length=512)),
                ('route_name', models.CharField(blank=True, default='', max_length=128)),
                ('api_schema_operation_id', models.CharField(blank=True, default='', max_length=128)),
                ('handler_ref', models.CharField(max_length=512)),
                ('domain_resource_names_json', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_endpoints', to='fervis_lineage.questionrun')),
            ],
            options={
                'db_table': 'fervis_catalog_endpoint',
            },
        ),
        migrations.CreateModel(
            name='AnswerOutput',
            fields=[
                ('answer_output_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('output_key', models.CharField(max_length=128)),
                ('value_kind', models.CharField(choices=[('entity', 'entity'), ('number', 'number'), ('money', 'money'), ('boolean', 'boolean'), ('text', 'text'), ('date', 'date'), ('datetime', 'datetime'), ('table', 'table'), ('list', 'list'), ('object', 'object')], max_length=64)),
                ('value_json', models.JSONField(default=dict)),
                ('proof_node_refs_json', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outputs', to='fervis_lineage.answer')),
                ('fact_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_outputs', to='fervis_lineage.factresult')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_outputs', to='fervis_lineage.questionrun')),
            ],
            options={
                'db_table': 'fervis_answer_output',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='fervis_lineage.questionrun'),
        ),
        migrations.CreateModel(
            name='RequestedFact',
            fields=[
                ('requested_fact_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('fact_key', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('answer_expression_family', models.CharField(max_length=64)),
                ('requested_fact_json', models.JSONField(blank=True, default=dict)),
                ('answer_requests_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_facts', to='fervis_lineage.questionrun')),
            ],
            options={
                'db_table': 'fervis_requested_fact',
            },
        ),
        migrations.AddField(
            model_name='factresult',
            name='requested_fact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fact_results', to='fervis_lineage.requestedfact'),
        ),
        migrations.CreateModel(
            name='RunResult',
            fields=[
                ('run_result_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('result_kind', models.CharField(choices=[('answered', 'answered'), ('factual_terminal', 'factual_terminal'), ('runtime_error', 'runtime_error')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='run_result', to='fervis_lineage.questionrun')),
            ],
            options={
                'db_table': 'fervis_run_result',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='run_result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='answer', to='fervis_lineage.runresult'),
        ),
        migrations.CreateModel(
            name='RunStep',
            fields=[
                ('step_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('step_key', models.CharField(choices=[('conversation_resolution', 'conversation_resolution'), ('question_contract', 'question_contract'), ('query_enrichment', 'query_enrichment'), ('catalog_selection', 'catalog_selection'), ('grounding', 'grounding'), ('read_eligibility', 'read_eligibility'), ('plan_selection', 'plan_selection'), ('source_binding', 'source_binding'), ('fact_planning', 'fact_planning'), ('verify', 'verify'), ('compile', 'compile'), ('execute', 'execute'), ('classify', 'classify'), ('render', 'render'), ('answer_synthesis', 'answer_synthesis')], max_length=64)),
                ('attempt', models.PositiveIntegerField(blank=True, null=True)),
                ('scope_type', models.CharField(blank=True, choices=[('requested_fact', 'requested_fact'), ('source', 'source'), ('page', 'page')], default='', max_length=64)),
                ('scope_id', models.CharField(blank=True, default='', max_length=128)),
                ('kind', models.CharField(choices=[('model_turn', 'model_turn'), ('deterministic', 'deterministic')], max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('input_summary_json', models.JSONField(blank=True, default=dict)),
                ('output_summary_json', models.JSONField(blank=True, default=dict)),
                ('error_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='fervis_lineage.questionrun')),
            ],
            options={
                'db_table': 'fervis_run_step',
            },
        ),
        migrations.CreateModel(
            name='RunArtifact',
            fields=[
                ('artifact_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('artifact_kind', models.CharField(choices=[('system_prompt', 'system_prompt'), ('prompt', 'prompt'), ('schema', 'schema'), ('tool_spec', 'tool_spec'), ('submitted_payload', 'submitted_payload'), ('raw_output', 'raw_output'), ('parsed_payload', 'parsed_payload'), ('deterministic_input', 'deterministic_input'), ('deterministic_output', 'deterministic_output'), ('source_response', 'source_response'), ('row_context', 'row_context')], max_length=64)),
                ('content_hash', models.CharField(max_length=128)),
                ('content', models.TextField(blank=True, null=True)),
                ('storage_ref', models.CharField(blank=True, max_length=512, null=True)),
                ('content_type', models.CharField(max_length=128)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='fervis_lineage.modelcall')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='fervis_lineage.questionrun')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='fervis_lineage.runstep')),
            ],
            options={
                'db_table': 'fervis_run_artifact',
            },
        ),
        migrations.AddField(
            model_name='requestedfact',
            name='produced_by_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_facts', to='fervis_lineage.runstep'),
        ),
        migrations.AddField(
            model_name='modelcall',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_calls', to='fervis_lineage.runstep'),
        ),
        migrations.CreateModel(
            name='MemoryArtifact',
            fields=[
                ('memory_artifact_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('source_kind', models.CharField(choices=[('requested_fact', 'requested_fact'), ('known_input', 'known_input'), ('fact_result', 'fact_result'), ('run_terminal', 'run_terminal')], max_length=64)),
                ('payload_schema', models.CharField(max_length=128)),
                ('payload_schema_rev', models.PositiveIntegerField()),
                ('payload_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fact_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memory_artifacts', to='fervis_lineage.factresult')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memory_artifacts', to='fervis_lineage.questionrun')),
                ('requested_fact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memory_artifacts', to='fervis_lineage.requestedfact')),
                ('produced_by_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memory_artifacts', to='fervis_lineage.runstep')),
            ],
            options={
                'db_table': 'fervis_memory_artifact',
            },
        ),
        migrations.AddField(
            model_name='factresult',
            name='produced_by_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fact_results', to='fervis_lineage.runstep'),
        ),
        migrations.CreateModel(
            name='ExecutionProofGraph',
            fields=[
                ('proof_graph_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('payload_schema', models.CharField(max_length=128)),
                ('payload_schema_rev', models.PositiveIntegerField()),
                ('payload_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fact_result', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='execution_proof_graph', to='fervis_lineage.factresult')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_proof_graphs', to='fervis_lineage.questionrun')),
                ('compile_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compiled_proof_graphs', to='fervis_lineage.runstep')),
                ('execute_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executed_proof_graphs', to='fervis_lineage.runstep')),
            ],
            options={
                'db_table': 'fervis_execution_proof_graph',
            },
        ),
        migrations.AddField(
            model_name='clarificationrequest',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clarification_requests', to='fervis_lineage.runstep'),
        ),
        migrations.CreateModel(
            name='AnswerPresentation',
            fields=[
                ('presentation_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('client_key', models.CharField(choices=[('default', 'default'), ('api', 'api'), ('cli', 'cli'), ('web', 'web'), ('slack', 'slack')], default='default', max_length=64)),
                ('locale', models.CharField(default='default', max_length=32)),
                ('presentation_kind', models.CharField(choices=[('text', 'text'), ('table', 'table'), ('template', 'template'), ('formatted_number', 'formatted_number')], max_length=64)),
                ('rendered_value', models.TextField(blank=True, null=True)),
                ('payload_schema', models.CharField(blank=True, default='', max_length=128)),
                ('payload_schema_rev', models.PositiveIntegerField(blank=True, null=True)),
                ('payload_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presentations', to='fervis_lineage.answer')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_presentations', to='fervis_lineage.questionrun')),
                ('render_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_presentations', to='fervis_lineage.runstep')),
            ],
            options={
                'db_table': 'fervis_answer_presentation',
            },
        ),
        migrations.CreateModel(
            name='RuntimeErrorDetail',
            fields=[
                ('runtime_error_detail_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('error_kind', models.CharField(choices=[('planning_failed', 'planning_failed'), ('fact_plan_parse_failed', 'fact_plan_parse_failed'), ('plan_validation_failed', 'plan_validation_failed'), ('fact_plan_execution_failed', 'fact_plan_execution_failed'), ('fact_plan_verification_failed', 'fact_plan_verification_failed'), ('compiler_invariant_failed', 'compiler_invariant_failed'), ('incomplete_evidence', 'incomplete_evidence'), ('page_cap_truncation', 'page_cap_truncation'), ('provider_runtime_failed', 'provider_runtime_failed'), ('policy_limit_exceeded', 'policy_limit_exceeded'), ('framework_adapter_failed', 'framework_adapter_failed'), ('lineage_persistence_failed', 'lineage_persistence_failed'), ('infrastructure_failed', 'infrastructure_failed')], max_length=64)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('failed_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runtime_errors', to='fervis_lineage.runstep')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runtime_errors', to='fervis_lineage.questionrun')),
                ('run_result', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='runtime_error_detail', to='fervis_lineage.runresult')),
            ],
            options={
                'db_table': 'fervis_runtime_error_detail',
            },
        ),
        migrations.CreateModel(
            name='SourceRead',
            fields=[
                ('source_read_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('args_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('succeeded', 'succeeded'), ('failed', 'failed')], max_length=32)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('completeness_json', models.JSONField(blank=True, default=dict)),
                ('response_hash', models.CharField(blank=True, default='', max_length=128)),
                ('error_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_reads', to='fervis_lineage.runartifact')),
                ('catalog_endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_reads', to='fervis_lineage.catalogendpoint')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_reads', to='fervis_lineage.questionrun')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_reads', to='fervis_lineage.runstep')),
            ],
            options={
                'db_table': 'fervis_source_read',
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['conversation', 'conversation_sequence'], name='fervis_question_conv_seq_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('conversation', 'conversation_sequence'), name='fervis_question_conv_seq_uq'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('conversation', 'question_id'), name='fervis_question_conv_id_uq'),
        ),
        migrations.AddIndex(
            model_name='questionrun',
            index=models.Index(fields=['question', 'run_number'], name='fervis_run_question_num_idx'),
        ),
        migrations.AddIndex(
            model_name='questionrun',
            index=models.Index(fields=['base_run'], name='fervis_run_base_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionrun',
            constraint=models.UniqueConstraint(fields=('question', 'run_number'), name='fervis_run_question_num_uq'),
        ),
        migrations.AddConstraint(
            model_name='questionrun',
            constraint=models.UniqueConstraint(fields=('question', 'run_id'), name='fervis_run_question_id_unique'),
        ),
        migrations.AddIndex(
            model_name='modelcallusage',
            index=models.Index(fields=['run', 'model_call'], name='fervis_usage_call_idx'),
        ),
        migrations.AddIndex(
            model_name='modelcallusage',
            index=models.Index(fields=['usage_kind'], name='fervis_usage_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='modelcallusage',
            constraint=models.UniqueConstraint(fields=('run', 'usage_id'), name='fervis_usage_run_id_unique'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['tenant_id', 'created_at'], name='fervis_conv_tenant_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['parent_conversation'], name='fervis_conv_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='clarificationresponse',
            index=models.Index(fields=['run', 'clarification'], name='fervis_clar_resp_req_idx'),
        ),
        migrations.AddConstraint(
            model_name='clarificationresponse',
            constraint=models.UniqueConstraint(fields=('run', 'response_id'), name='fervis_clar_resp_run_id_uq'),
        ),
        migrations.AddIndex(
            model_name='catalogendpoint',
            index=models.Index(fields=['run'], name='fervis_cat_endpoint_run_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogendpoint',
            index=models.Index(fields=['framework_kind', 'source_namespace_kind'], name='fervis_cat_endpoint_fw_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogendpoint',
            index=models.Index(fields=['endpoint_name'], name='fervis_cat_endpoint_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogendpoint',
            constraint=models.UniqueConstraint(fields=('run', 'catalog_endpoint_id'), name='fervis_cat_endpoint_run_id_uq'),
        ),
        migrations.AddConstraint(
            model_name='catalogendpoint',
            constraint=models.UniqueConstraint(fields=('run', 'catalog_endpoint_key'), name='fervis_cat_endpoint_run_key_uq'),
        ),
        migrations.AddIndex(
            model_name='answeroutput',
            index=models.Index(fields=['run', 'answer'], name='fervis_answer_output_ans_idx'),
        ),
        migrations.AddIndex(
            model_name='answeroutput',
            index=models.Index(fields=['run', 'fact_result'], name='fervis_answer_output_fact_idx'),
        ),
        migrations.AddConstraint(
            model_name='answeroutput',
            constraint=models.UniqueConstraint(fields=('run', 'answer_output_id'), name='fervis_answer_output_run_id_uq'),
        ),
        migrations.AddConstraint(
            model_name='answeroutput',
            constraint=models.UniqueConstraint(fields=('run', 'answer', 'output_key'), name='fervis_answer_output_key_uq'),
        ),
        migrations.AddConstraint(
            model_name='runresult',
            constraint=models.UniqueConstraint(fields=('run', 'run_result_id'), name='fervis_run_result_run_id_uq'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('run', 'answer_id'), name='fervis_answer_run_id_uq'),
        ),
        migrations.AddIndex(
            model_name='runstep',
            index=models.Index(fields=['run', 'step_key'], name='fervis_step_run_key_idx'),
        ),
        migrations.AddIndex(
            model_name='runstep',
            index=models.Index(fields=['run', 'step_key', 'scope_type', 'scope_id'], name='fervis_step_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='runstep',
            constraint=models.UniqueConstraint(fields=('run', 'sequence'), name='fervis_step_run_seq_uq'),
        ),
        migrations.AddConstraint(
            model_name='runstep',
            constraint=models.UniqueConstraint(fields=('run', 'step_id'), name='fervis_step_run_id_unique'),
        ),
        migrations.AddIndex(
            model_name='runartifact',
            index=models.Index(fields=['run', 'step'], name='fervis_artifact_step_idx'),
        ),
        migrations.AddIndex(
            model_name='runartifact',
            index=models.Index(fields=['model_call', 'artifact_kind'], name='fervis_artifact_call_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='runartifact',
            constraint=models.UniqueConstraint(fields=('run', 'artifact_id'), name='fervis_artifact_run_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='runartifact',
            constraint=models.UniqueConstraint(fields=('run', 'step', 'artifact_id'), name='fervis_artifact_step_id_uq'),
        ),
        migrations.AddConstraint(
            model_name='runartifact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('content__isnull', False), ('storage_ref__isnull', True)), models.Q(('content__isnull', True), ('storage_ref__isnull', False), models.Q(('storage_ref', ''), _negated=True)), _connector='OR'), name='fervis_artifact_one_body'),
        ),
        migrations.AddIndex(
            model_name='requestedfact',
            index=models.Index(fields=['run', 'fact_key'], name='fervis_req_fact_key_idx'),
        ),
        migrations.AddConstraint(
            model_name='requestedfact',
            constraint=models.UniqueConstraint(fields=('run', 'requested_fact_id'), name='fervis_req_fact_run_id_uq'),
        ),
        migrations.AddConstraint(
            model_name='requestedfact',
            constraint=models.UniqueConstraint(fields=('run', 'produced_by_step', 'fact_key'), name='fervis_req_fact_step_key_uq'),
        ),
        migrations.AddIndex(
            model_name='modelcall',
            index=models.Index(fields=['run', 'step'], name='fervis_model_call_step_idx'),
        ),
        migrations.AddIndex(
            model_name='modelcall',
            index=models.Index(fields=['provider', 'model_key'], name='fervis_model_call_provider_idx'),
        ),
        migrations.AddConstraint(
            model_name='modelcall',
            constraint=models.UniqueConstraint(fields=('run', 'model_call_id'), name='fervis_call_run_id_uq'),
        ),
        migrations.AddConstraint(
            model_name='modelcall',
            constraint=models.UniqueConstraint(fields=('run', 'step', 'model_call_id'), name='fervis_call_step_id_uq'),
        ),
        migrations.AddConstraint(
            model_name='modelcall',
            constraint=models.UniqueConstraint(fields=('run', 'step', 'call_index'), name='fervis_call_step_idx_uq'),
        ),
        migrations.AddIndex(
            model_name='memoryartifact',
            index=models.Index(fields=['run', 'source_kind'], name='fervis_memory_art_source_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryartifact',
            index=models.Index(fields=['run', 'requested_fact'], name='fervis_memory_art_req_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryartifact',
            index=models.Index(fields=['run', 'fact_result'], name='fervis_memory_art_result_idx'),
        ),
        migrations.AddConstraint(
            model_name='memoryartifact',
            constraint=models.UniqueConstraint(fields=('run', 'memory_artifact_id'), name='fervis_memory_art_run_id_uq'),
        ),
        migrations.AddIndex(
            model_name='factresult',
            index=models.Index(fields=['run', 'requested_fact'], name='fervis_fact_result_fact_idx'),
        ),
        migrations.AddIndex(
            model_name='factresult',
            index=models.Index(fields=['run', 'result_kind'], name='fervis_fact_result_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='factresult',
            constraint=models.UniqueConstraint(fields=('run', 'fact_result_id'), name='fervis_fact_result_run_id_uq'),
        ),
        migrations.AddIndex(
            model_name='executionproofgraph',
            index=models.Index(fields=['run', 'fact_result'], name='fervis_proof_fact_idx'),
        ),
        migrations.AddConstraint(
            model_name='executionproofgraph',
            constraint=models.UniqueConstraint(fields=('run', 'proof_graph_id'), name='fervis_proof_graph_run_id_uq'),
        ),
        migrations.AddIndex(
            model_name='clarificationrequest',
            index=models.Index(fields=['run', 'need'], name='fervis_clar_req_need_idx'),
        ),
        migrations.AddIndex(
            model_name='clarificationrequest',
            index=models.Index(fields=['run', 'reason'], name='fervis_clar_req_reason_idx'),
        ),
        migrations.AddConstraint(
            model_name='clarificationrequest',
            constraint=models.UniqueConstraint(fields=('run', 'clarification_id'), name='fervis_clar_req_run_id_uq'),
        ),
        migrations.AddIndex(
            model_name='answerpresentation',
            index=models.Index(fields=['run', 'answer'], name='fervis_answer_pres_ans_idx'),
        ),
        migrations.AddConstraint(
            model_name='answerpresentation',
            constraint=models.UniqueConstraint(fields=('run', 'presentation_id'), name='fervis_answer_pres_run_id_uq'),
        ),
        migrations.AddConstraint(
            model_name='answerpresentation',
            constraint=models.UniqueConstraint(fields=('run', 'answer', 'client_key', 'locale', 'presentation_kind'), name='fervis_answer_pres_shape_uq'),
        ),
        migrations.AddConstraint(
            model_name='answerpresentation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payload_json__isnull', True), ('rendered_value__isnull', False)), models.Q(('payload_json__isnull', False), ('rendered_value__isnull', True)), _connector='OR'), name='fervis_answer_pres_body_ck'),
        ),
        migrations.AddIndex(
            model_name='runtimeerrordetail',
            index=models.Index(fields=['run', 'failed_step'], name='fervis_runtime_error_step_idx'),
        ),
        migrations.AddConstraint(
            model_name='runtimeerrordetail',
            constraint=models.UniqueConstraint(fields=('run', 'runtime_error_detail_id'), name='fervis_runtime_err_run_id_uq'),
        ),
        migrations.AddIndex(
            model_name='sourceread',
            index=models.Index(fields=['run', 'step'], name='fervis_source_read_step_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceread',
            index=models.Index(fields=['catalog_endpoint'], name='fervis_src_read_catalog_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourceread',
            constraint=models.UniqueConstraint(fields=('run', 'source_read_id'), name='fervis_src_read_run_id_uq'),
        ),
    ]
