# Generated by Django 5.2 on 2026-06-20 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelCall",
            fields=[
                (
                    "model_call_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("call_index", models.PositiveIntegerField()),
                ("provider", models.CharField(max_length=64)),
                ("model_key", models.CharField(max_length=128)),
                (
                    "provider_request_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("succeeded", "succeeded"), ("failed", "failed")],
                        max_length=32,
                    ),
                ),
                (
                    "finish_reason",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "reasoning_effort",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "reasoning_budget_tokens",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "max_output_tokens",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("prompt_chars", models.PositiveIntegerField(default=0)),
                ("schema_chars", models.PositiveIntegerField(default=0)),
                (
                    "submitted_payload_chars",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "raw_output_chars",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "fervis_model_call",
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "conversation_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=128)),
                (
                    "origin_kind",
                    models.CharField(
                        choices=[("initial", "initial"), ("fork", "fork")],
                        default="initial",
                        max_length=32,
                    ),
                ),
                (
                    "origin_ref",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent_conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="forks",
                        to="fervis_lineage.conversation",
                    ),
                ),
            ],
            options={
                "db_table": "fervis_conversation",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "question_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("conversation_sequence", models.PositiveIntegerField()),
                (
                    "origin_message_ref",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("original_question", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="fervis_lineage.conversation",
                    ),
                ),
            ],
            options={
                "db_table": "fervis_question",
            },
        ),
        migrations.AddField(
            model_name="conversation",
            name="forked_after_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conversation_forks",
                to="fervis_lineage.question",
            ),
        ),
        migrations.CreateModel(
            name="QuestionRun",
            fields=[
                (
                    "run_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("run_number", models.PositiveIntegerField()),
                (
                    "trigger_kind",
                    models.CharField(
                        choices=[
                            ("initial", "initial"),
                            ("clarification_response", "clarification_response"),
                            ("retry", "retry"),
                            ("rerun", "rerun"),
                            ("replay", "replay"),
                        ],
                        default="initial",
                        max_length=32,
                    ),
                ),
                (
                    "trigger_clarification_response_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("integrated_question", models.TextField()),
                ("adapter_ref", models.CharField(max_length=128)),
                ("runtime_version", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "previous_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="triggered_runs",
                        to="fervis_lineage.questionrun",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="fervis_lineage.question",
                    ),
                ),
                (
                    "trigger_clarification_response_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clarification_triggered_runs",
                        to="fervis_lineage.questionrun",
                    ),
                ),
            ],
            options={
                "db_table": "fervis_question_run",
            },
        ),
        migrations.CreateModel(
            name="ModelCallUsage",
            fields=[
                (
                    "usage_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                (
                    "usage_kind",
                    models.CharField(
                        choices=[
                            ("input_tokens", "input_tokens"),
                            ("cached_input_tokens", "cached_input_tokens"),
                            ("output_tokens", "output_tokens"),
                            ("reasoning_tokens", "reasoning_tokens"),
                            ("thinking_tokens", "thinking_tokens"),
                            ("tool_tokens", "tool_tokens"),
                        ],
                        max_length=64,
                    ),
                ),
                ("quantity", models.PositiveBigIntegerField()),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("tokens", "tokens"),
                            ("chars", "chars"),
                            ("calls", "calls"),
                        ],
                        max_length=32,
                    ),
                ),
                ("provider_usage_key", models.CharField(max_length=128)),
                ("cost_micros", models.BigIntegerField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, default="", max_length=16)),
                ("price_basis_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model_call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usage_rows",
                        to="fervis_lineage.modelcall",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="model_call_usages",
                        to="fervis_lineage.questionrun",
                    ),
                ),
            ],
            options={
                "db_table": "fervis_model_call_usage",
            },
        ),
        migrations.AddField(
            model_name="modelcall",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="model_calls",
                to="fervis_lineage.questionrun",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="forked_after_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conversation_forks",
                to="fervis_lineage.questionrun",
            ),
        ),
        migrations.CreateModel(
            name="RunResult",
            fields=[
                (
                    "run_result_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                (
                    "result_kind",
                    models.CharField(
                        choices=[
                            ("answered", "answered"),
                            ("factual_terminal", "factual_terminal"),
                            ("runtime_error", "runtime_error"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="run_result",
                        to="fervis_lineage.questionrun",
                    ),
                ),
            ],
            options={
                "db_table": "fervis_run_result",
            },
        ),
        migrations.CreateModel(
            name="RunStep",
            fields=[
                (
                    "step_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("sequence", models.PositiveIntegerField()),
                (
                    "step_key",
                    models.CharField(
                        choices=[
                            ("conversation_resolution", "conversation_resolution"),
                            ("question_contract", "question_contract"),
                            ("query_enrichment", "query_enrichment"),
                            ("catalog_selection", "catalog_selection"),
                            ("grounding", "grounding"),
                            ("read_eligibility", "read_eligibility"),
                            ("plan_selection", "plan_selection"),
                            ("source_binding", "source_binding"),
                            ("fact_planning", "fact_planning"),
                            ("verify", "verify"),
                            ("compile", "compile"),
                            ("execute", "execute"),
                            ("classify", "classify"),
                            ("render", "render"),
                            ("answer_synthesis", "answer_synthesis"),
                        ],
                        max_length=64,
                    ),
                ),
                ("attempt", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "scope_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("requested_fact", "requested_fact"),
                            ("source", "source"),
                            ("page", "page"),
                        ],
                        default="",
                        max_length=64,
                    ),
                ),
                ("scope_id", models.CharField(blank=True, default="", max_length=128)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("model_turn", "model_turn"),
                            ("deterministic", "deterministic"),
                        ],
                        max_length=32,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("input_summary_json", models.JSONField(blank=True, default=dict)),
                ("output_summary_json", models.JSONField(blank=True, default=dict)),
                ("error_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="steps",
                        to="fervis_lineage.questionrun",
                    ),
                ),
            ],
            options={
                "db_table": "fervis_run_step",
            },
        ),
        migrations.CreateModel(
            name="RunArtifact",
            fields=[
                (
                    "artifact_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                (
                    "artifact_kind",
                    models.CharField(
                        choices=[
                            ("system_prompt", "system_prompt"),
                            ("prompt", "prompt"),
                            ("schema", "schema"),
                            ("tool_spec", "tool_spec"),
                            ("submitted_payload", "submitted_payload"),
                            ("raw_output", "raw_output"),
                            ("parsed_payload", "parsed_payload"),
                            ("deterministic_input", "deterministic_input"),
                            ("deterministic_output", "deterministic_output"),
                            ("source_response", "source_response"),
                            ("row_context", "row_context"),
                            ("compiled_execution", "compiled_execution"),
                        ],
                        max_length=64,
                    ),
                ),
                ("content_hash", models.CharField(max_length=128)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "storage_ref",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("content_type", models.CharField(max_length=128)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model_call",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="artifacts",
                        to="fervis_lineage.modelcall",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="artifacts",
                        to="fervis_lineage.questionrun",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="artifacts",
                        to="fervis_lineage.runstep",
                    ),
                ),
            ],
            options={
                "db_table": "fervis_run_artifact",
            },
        ),
        migrations.AddField(
            model_name="modelcall",
            name="step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="model_calls",
                to="fervis_lineage.runstep",
            ),
        ),
        migrations.CreateModel(
            name="RuntimeErrorDetail",
            fields=[
                (
                    "runtime_error_detail_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                (
                    "error_kind",
                    models.CharField(
                        choices=[
                            ("fact_plan_parse_failed", "fact_plan_parse_failed"),
                            (
                                "fact_plan_verification_failed",
                                "fact_plan_verification_failed",
                            ),
                            ("compiler_invariant_failed", "compiler_invariant_failed"),
                            ("incomplete_evidence", "incomplete_evidence"),
                            ("page_cap_truncation", "page_cap_truncation"),
                            ("provider_runtime_failed", "provider_runtime_failed"),
                            ("framework_adapter_failed", "framework_adapter_failed"),
                            ("infrastructure_failed", "infrastructure_failed"),
                        ],
                        max_length=64,
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "failed_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runtime_errors",
                        to="fervis_lineage.runstep",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runtime_errors",
                        to="fervis_lineage.questionrun",
                    ),
                ),
                (
                    "run_result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runtime_error_detail",
                        to="fervis_lineage.runresult",
                    ),
                ),
            ],
            options={
                "db_table": "fervis_runtime_error_detail",
            },
        ),
        migrations.CreateModel(
            name="SourceRead",
            fields=[
                (
                    "source_read_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("endpoint_id", models.CharField(max_length=128)),
                ("args_json", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("succeeded", "succeeded"), ("failed", "failed")],
                        max_length=32,
                    ),
                ),
                ("row_count", models.PositiveIntegerField(blank=True, null=True)),
                ("completeness_json", models.JSONField(blank=True, default=dict)),
                (
                    "response_hash",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("error_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artifact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_reads",
                        to="fervis_lineage.runartifact",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_reads",
                        to="fervis_lineage.questionrun",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_reads",
                        to="fervis_lineage.runstep",
                    ),
                ),
            ],
            options={
                "db_table": "fervis_source_read",
            },
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["conversation", "conversation_sequence"],
                name="fervis_question_conv_seq_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                fields=("conversation", "conversation_sequence"),
                name="fervis_question_conv_seq_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                fields=("conversation", "question_id"),
                name="fervis_question_conv_id_uq",
            ),
        ),
        migrations.AddIndex(
            model_name="questionrun",
            index=models.Index(
                fields=["question", "run_number"], name="fervis_run_question_num_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="questionrun",
            index=models.Index(fields=["previous_run"], name="fervis_run_previous_idx"),
        ),
        migrations.AddIndex(
            model_name="questionrun",
            index=models.Index(
                fields=["trigger_clarification_response_run"],
                name="fervis_run_clarify_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionrun",
            constraint=models.UniqueConstraint(
                fields=("question", "run_number"), name="fervis_run_question_num_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="questionrun",
            constraint=models.UniqueConstraint(
                fields=("question", "run_id"), name="fervis_run_question_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="questionrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("previous_run__isnull", True),
                        ("trigger_clarification_response_id", ""),
                        ("trigger_clarification_response_run__isnull", True),
                        ("trigger_kind", "initial"),
                    ),
                    models.Q(
                        ("previous_run__isnull", False),
                        ("trigger_clarification_response_id", ""),
                        ("trigger_clarification_response_run__isnull", True),
                        ("trigger_kind__in", ["retry", "rerun", "replay"]),
                    ),
                    models.Q(
                        ("previous_run__isnull", True),
                        ("trigger_clarification_response_run__isnull", False),
                        ("trigger_kind", "clarification_response"),
                        models.Q(
                            ("trigger_clarification_response_id", ""), _negated=True
                        ),
                    ),
                    _connector="OR",
                ),
                name="fervis_run_trigger_shape",
            ),
        ),
        migrations.AddIndex(
            model_name="modelcallusage",
            index=models.Index(
                fields=["run", "model_call"], name="fervis_usage_call_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelcallusage",
            index=models.Index(fields=["usage_kind"], name="fervis_usage_kind_idx"),
        ),
        migrations.AddConstraint(
            model_name="modelcallusage",
            constraint=models.UniqueConstraint(
                fields=("run", "usage_id"), name="fervis_usage_run_id_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["tenant_id", "created_at"], name="fervis_conv_tenant_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["parent_conversation"], name="fervis_conv_parent_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("forked_after_question__isnull", True),
                        ("forked_after_run__isnull", True),
                        ("origin_kind", "initial"),
                        ("parent_conversation__isnull", True),
                    ),
                    models.Q(
                        ("forked_after_question__isnull", False),
                        ("forked_after_run__isnull", False),
                        ("origin_kind", "fork"),
                        ("parent_conversation__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="fervis_conv_origin_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="runresult",
            constraint=models.UniqueConstraint(
                fields=("run", "run_result_id"), name="fervis_run_result_run_id_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="runstep",
            index=models.Index(
                fields=["run", "step_key"], name="fervis_step_run_key_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="runstep",
            index=models.Index(
                fields=["run", "step_key", "scope_type", "scope_id"],
                name="fervis_step_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="runstep",
            constraint=models.UniqueConstraint(
                fields=("run", "sequence"), name="fervis_step_run_seq_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="runstep",
            constraint=models.UniqueConstraint(
                fields=("run", "step_id"), name="fervis_step_run_id_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="runartifact",
            index=models.Index(fields=["run", "step"], name="fervis_artifact_step_idx"),
        ),
        migrations.AddIndex(
            model_name="runartifact",
            index=models.Index(
                fields=["model_call", "artifact_kind"],
                name="fervis_artifact_call_kind_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="runartifact",
            constraint=models.UniqueConstraint(
                fields=("run", "artifact_id"), name="fervis_artifact_run_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="runartifact",
            constraint=models.UniqueConstraint(
                fields=("run", "step", "artifact_id"), name="fervis_artifact_step_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="runartifact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("content__isnull", False), ("storage_ref__isnull", True)),
                    models.Q(
                        ("content__isnull", True),
                        ("storage_ref__isnull", False),
                        models.Q(("storage_ref", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="fervis_artifact_one_body",
            ),
        ),
        migrations.AddConstraint(
            model_name="runartifact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        (
                            "artifact_kind__in",
                            (
                                "system_prompt",
                                "prompt",
                                "schema",
                                "tool_spec",
                                "submitted_payload",
                                "raw_output",
                                "parsed_payload",
                            ),
                        ),
                        ("model_call__isnull", False),
                    ),
                    models.Q(
                        (
                            "artifact_kind__in",
                            (
                                "system_prompt",
                                "prompt",
                                "schema",
                                "tool_spec",
                                "submitted_payload",
                                "raw_output",
                                "parsed_payload",
                            ),
                        ),
                        _negated=True,
                    ),
                    _connector="OR",
                ),
                name="fervis_artifact_model_call_shape",
            ),
        ),
        migrations.AddIndex(
            model_name="modelcall",
            index=models.Index(
                fields=["run", "step"], name="fervis_model_call_step_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelcall",
            index=models.Index(
                fields=["provider", "model_key"], name="fervis_model_call_provider_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="modelcall",
            constraint=models.UniqueConstraint(
                fields=("run", "model_call_id"), name="fervis_call_run_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="modelcall",
            constraint=models.UniqueConstraint(
                fields=("run", "step", "model_call_id"), name="fervis_call_step_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="modelcall",
            constraint=models.UniqueConstraint(
                fields=("run", "step", "call_index"), name="fervis_call_step_idx_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="runtimeerrordetail",
            index=models.Index(
                fields=["run", "failed_step"], name="fervis_runtime_error_step_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="runtimeerrordetail",
            constraint=models.UniqueConstraint(
                fields=("run", "runtime_error_detail_id"),
                name="fervis_runtime_err_run_id_uq",
            ),
        ),
        migrations.AddIndex(
            model_name="sourceread",
            index=models.Index(
                fields=["run", "step"], name="fervis_source_read_step_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sourceread",
            index=models.Index(
                fields=["endpoint_id"], name="fervis_src_read_endpoint_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceread",
            constraint=models.UniqueConstraint(
                fields=("run", "source_read_id"), name="fervis_src_read_run_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceread",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "failed"),
                    models.Q(
                        ("status", "succeeded"),
                        ("row_count__isnull", False),
                        models.Q(("response_hash", ""), _negated=True),
                        models.Q(("completeness_json", {}), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="fervis_src_read_success_shape",
            ),
        ),
    ]
