# Generated by Django 5.2 on 2026-06-20 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fervis_lineage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "answer_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answers",
                        to="fervis_lineage.questionrun",
                    ),
                ),
                (
                    "run_result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answer",
                        to="fervis_lineage.runresult",
                    ),
                ),
            ],
            options={
                "db_table": "fervis_answer",
            },
        ),
        migrations.CreateModel(
            name="AnswerPresentation",
            fields=[
                (
                    "presentation_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                (
                    "client_key",
                    models.CharField(
                        choices=[
                            ("default", "default"),
                            ("api", "api"),
                            ("cli", "cli"),
                            ("web", "web"),
                            ("slack", "slack"),
                        ],
                        default="default",
                        max_length=64,
                    ),
                ),
                ("locale", models.CharField(default="default", max_length=32)),
                (
                    "presentation_kind",
                    models.CharField(
                        choices=[
                            ("text", "text"),
                            ("table", "table"),
                            ("template", "template"),
                            ("formatted_number", "formatted_number"),
                        ],
                        max_length=64,
                    ),
                ),
                ("rendered_value", models.TextField(blank=True, null=True)),
                (
                    "payload_schema",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "payload_schema_rev",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("payload_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="presentations",
                        to="fervis_lineage.answer",
                    ),
                ),
                (
                    "render_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answer_presentations",
                        to="fervis_lineage.runstep",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answer_presentations",
                        to="fervis_lineage.questionrun",
                    ),
                ),
            ],
            options={
                "db_table": "fervis_answer_presentation",
            },
        ),
        migrations.CreateModel(
            name="ClarificationRequest",
            fields=[
                (
                    "clarification_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                (
                    "basis",
                    models.CharField(
                        choices=[
                            ("missing_answer_metric", "missing_answer_metric"),
                            (
                                "missing_comparison_baseline",
                                "missing_comparison_baseline",
                            ),
                            ("catalog_requires_choice", "catalog_requires_choice"),
                            (
                                "multiple_matching_entities",
                                "multiple_matching_entities",
                            ),
                            ("unresolved_reference", "unresolved_reference"),
                            ("missing_required_value", "missing_required_value"),
                            ("unsupported_reference", "unsupported_reference"),
                        ],
                        max_length=64,
                    ),
                ),
                ("question_text", models.TextField()),
                ("options_json", models.JSONField(blank=True, default=list)),
                ("evidence_refs_json", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clarification_requests",
                        to="fervis_lineage.questionrun",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clarification_requests",
                        to="fervis_lineage.runstep",
                    ),
                ),
            ],
            options={
                "db_table": "fervis_clarification_request",
            },
        ),
        migrations.CreateModel(
            name="ClarificationResponse",
            fields=[
                (
                    "response_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                (
                    "source_message_ref",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "selected_option_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("response_text", models.TextField(blank=True, default="")),
                ("evidence_ref", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clarification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responses",
                        to="fervis_lineage.clarificationrequest",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clarification_responses",
                        to="fervis_lineage.questionrun",
                    ),
                ),
            ],
            options={
                "db_table": "fervis_clarification_response",
            },
        ),
        migrations.CreateModel(
            name="FactResult",
            fields=[
                (
                    "fact_result_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                (
                    "result_kind",
                    models.CharField(
                        choices=[
                            ("answered", "answered"),
                            ("needs_clarification", "needs_clarification"),
                            ("impossible", "impossible"),
                            ("no_data", "no_data"),
                            ("undefined", "undefined"),
                        ],
                        max_length=64,
                    ),
                ),
                ("evidence_refs_json", models.JSONField(blank=True, default=list)),
                (
                    "payload_schema",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "payload_schema_rev",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("payload_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "produced_by_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fact_results",
                        to="fervis_lineage.runstep",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fact_results",
                        to="fervis_lineage.questionrun",
                    ),
                ),
            ],
            options={
                "db_table": "fervis_fact_result",
            },
        ),
        migrations.CreateModel(
            name="ExecutionProofGraph",
            fields=[
                (
                    "proof_graph_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("payload_schema", models.CharField(max_length=128)),
                ("payload_schema_rev", models.PositiveIntegerField()),
                ("payload_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "compile_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compiled_proof_graphs",
                        to="fervis_lineage.runstep",
                    ),
                ),
                (
                    "execute_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="executed_proof_graphs",
                        to="fervis_lineage.runstep",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execution_proof_graphs",
                        to="fervis_lineage.questionrun",
                    ),
                ),
                (
                    "fact_result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execution_proof_graph",
                        to="fervis_lineage.factresult",
                    ),
                ),
            ],
            options={
                "db_table": "fervis_execution_proof_graph",
            },
        ),
        migrations.AddField(
            model_name="clarificationrequest",
            name="fact_result",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clarification_requests",
                to="fervis_lineage.factresult",
            ),
        ),
        migrations.CreateModel(
            name="AnswerOutput",
            fields=[
                (
                    "answer_output_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("output_key", models.CharField(max_length=128)),
                (
                    "value_kind",
                    models.CharField(
                        choices=[
                            ("entity", "entity"),
                            ("number", "number"),
                            ("money", "money"),
                            ("boolean", "boolean"),
                            ("text", "text"),
                            ("date", "date"),
                            ("datetime", "datetime"),
                            ("table", "table"),
                            ("list", "list"),
                            ("object", "object"),
                        ],
                        max_length=64,
                    ),
                ),
                ("value_json", models.JSONField(default=dict)),
                ("proof_node_refs_json", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outputs",
                        to="fervis_lineage.answer",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answer_outputs",
                        to="fervis_lineage.questionrun",
                    ),
                ),
                (
                    "fact_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answer_outputs",
                        to="fervis_lineage.factresult",
                    ),
                ),
            ],
            options={
                "db_table": "fervis_answer_output",
            },
        ),
        migrations.CreateModel(
            name="RequestedFact",
            fields=[
                (
                    "requested_fact_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("fact_key", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, default="")),
                ("answer_expression_family", models.CharField(max_length=64)),
                ("requested_fact_json", models.JSONField(blank=True, default=dict)),
                ("answer_requests_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "produced_by_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_facts",
                        to="fervis_lineage.runstep",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_facts",
                        to="fervis_lineage.questionrun",
                    ),
                ),
            ],
            options={
                "db_table": "fervis_requested_fact",
            },
        ),
        migrations.AddField(
            model_name="factresult",
            name="requested_fact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fact_results",
                to="fervis_lineage.requestedfact",
            ),
        ),
        migrations.AddConstraint(
            model_name="answer",
            constraint=models.UniqueConstraint(
                fields=("run", "answer_id"), name="fervis_answer_run_id_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="answerpresentation",
            index=models.Index(
                fields=["run", "answer"], name="fervis_answer_pres_ans_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="answerpresentation",
            constraint=models.UniqueConstraint(
                fields=("run", "presentation_id"), name="fervis_answer_pres_run_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="answerpresentation",
            constraint=models.UniqueConstraint(
                fields=("run", "answer", "client_key", "locale", "presentation_kind"),
                name="fervis_answer_pres_shape_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="answerpresentation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("payload_json__isnull", True),
                        ("rendered_value__isnull", False),
                    ),
                    models.Q(
                        ("payload_json__isnull", False),
                        ("rendered_value__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="fervis_answer_pres_body_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="clarificationresponse",
            index=models.Index(
                fields=["run", "clarification"], name="fervis_clar_resp_req_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="clarificationresponse",
            constraint=models.UniqueConstraint(
                fields=("run", "response_id"), name="fervis_clar_resp_run_id_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="executionproofgraph",
            index=models.Index(
                fields=["run", "fact_result"], name="fervis_proof_fact_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="executionproofgraph",
            constraint=models.UniqueConstraint(
                fields=("run", "proof_graph_id"), name="fervis_proof_graph_run_id_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="clarificationrequest",
            index=models.Index(
                fields=["run", "basis"], name="fervis_clar_req_basis_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="clarificationrequest",
            constraint=models.UniqueConstraint(
                fields=("run", "clarification_id"), name="fervis_clar_req_run_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="clarificationrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("fact_result__isnull", False), ("step__isnull", True)),
                    models.Q(("fact_result__isnull", True), ("step__isnull", False)),
                    _connector="OR",
                ),
                name="fervis_clar_req_scope_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="answeroutput",
            index=models.Index(
                fields=["run", "answer"], name="fervis_answer_output_ans_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="answeroutput",
            index=models.Index(
                fields=["run", "fact_result"], name="fervis_answer_output_fact_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="answeroutput",
            constraint=models.UniqueConstraint(
                fields=("run", "answer_output_id"),
                name="fervis_answer_output_run_id_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="answeroutput",
            constraint=models.UniqueConstraint(
                fields=("run", "answer", "output_key"),
                name="fervis_answer_output_key_uq",
            ),
        ),
        migrations.AddIndex(
            model_name="requestedfact",
            index=models.Index(
                fields=["run", "fact_key"], name="fervis_req_fact_key_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="requestedfact",
            constraint=models.UniqueConstraint(
                fields=("run", "requested_fact_id"), name="fervis_req_fact_run_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="requestedfact",
            constraint=models.UniqueConstraint(
                fields=("run", "produced_by_step", "fact_key"),
                name="fervis_req_fact_step_key_uq",
            ),
        ),
        migrations.AddIndex(
            model_name="factresult",
            index=models.Index(
                fields=["run", "requested_fact"], name="fervis_fact_result_fact_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factresult",
            index=models.Index(
                fields=["run", "result_kind"], name="fervis_fact_result_kind_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="factresult",
            constraint=models.UniqueConstraint(
                fields=("run", "fact_result_id"), name="fervis_fact_result_run_id_uq"
            ),
        ),
    ]
