# Generated by Django 5.2 on 2026-06-20 11:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "fervis_lineage",
            "0002_answer_answerpresentation_clarificationrequest_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="clarificationrequest",
            name="fervis_clar_req_scope_ck",
        ),
        migrations.RemoveConstraint(
            model_name="conversation",
            name="fervis_conv_origin_shape",
        ),
        migrations.RemoveConstraint(
            model_name="questionrun",
            name="fervis_run_trigger_shape",
        ),
        migrations.RemoveConstraint(
            model_name="runartifact",
            name="fervis_artifact_model_call_shape",
        ),
        migrations.RemoveConstraint(
            model_name="sourceread",
            name="fervis_src_read_success_shape",
        ),
    ]
