# Generated by Django 5.2 on 2026-06-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "fervis_lineage",
            "0003_remove_clarificationrequest_fervis_clar_req_scope_ck_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="runtimeerrordetail",
            name="error_kind",
            field=models.CharField(
                choices=[
                    ("fact_plan_parse_failed", "fact_plan_parse_failed"),
                    ("plan_validation_failed", "plan_validation_failed"),
                    ("fact_plan_execution_failed", "fact_plan_execution_failed"),
                    ("fact_plan_verification_failed", "fact_plan_verification_failed"),
                    ("compiler_invariant_failed", "compiler_invariant_failed"),
                    ("incomplete_evidence", "incomplete_evidence"),
                    ("page_cap_truncation", "page_cap_truncation"),
                    ("provider_runtime_failed", "provider_runtime_failed"),
                    ("framework_adapter_failed", "framework_adapter_failed"),
                    ("lineage_persistence_failed", "lineage_persistence_failed"),
                    ("infrastructure_failed", "infrastructure_failed"),
                ],
                max_length=64,
            ),
        ),
    ]
