# Generated by Django 5.2.15 on 2026-09-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fervis_lineage', '0003_clarification_successor_runs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runstep',
            name='step_key',
            field=models.CharField(choices=[('conversation_resolution', 'conversation_resolution'), ('question_contract', 'question_contract'), ('query_enrichment', 'query_enrichment'), ('catalog_selection', 'catalog_selection'), ('grounding', 'grounding'), ('read_eligibility', 'read_eligibility'), ('plan_selection', 'plan_selection'), ('source_realization', 'source_realization'), ('source_binding', 'source_binding'), ('verify', 'verify'), ('compile', 'compile'), ('execute', 'execute'), ('classify', 'classify'), ('render', 'render'), ('answer_synthesis', 'answer_synthesis')], max_length=64),
        ),
    ]
