# Generated by Django 5.2 on 2026-06-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fervis_lineage", "0004_alter_runtimeerrordetail_error_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelcall",
            name="tool_spec_chars",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
