# Generated by Django 5.2 on 2026-06-20 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fervis_lineage", "0005_modelcall_tool_spec_chars"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemoryArtifact",
            fields=[
                (
                    "memory_artifact_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("requested_fact", "requested_fact"),
                            ("known_input", "known_input"),
                            ("fact_result", "fact_result"),
                            ("run_terminal", "run_terminal"),
                        ],
                        max_length=64,
                    ),
                ),
                ("payload_schema", models.CharField(max_length=128)),
                ("payload_schema_rev", models.PositiveIntegerField()),
                ("payload_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fact_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memory_artifacts",
                        to="fervis_lineage.factresult",
                    ),
                ),
                (
                    "produced_by_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memory_artifacts",
                        to="fervis_lineage.runstep",
                    ),
                ),
                (
                    "requested_fact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memory_artifacts",
                        to="fervis_lineage.requestedfact",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memory_artifacts",
                        to="fervis_lineage.questionrun",
                    ),
                ),
            ],
            options={
                "db_table": "fervis_memory_artifact",
                "indexes": [
                    models.Index(
                        fields=["run", "source_kind"],
                        name="fervis_memory_art_source_idx",
                    ),
                    models.Index(
                        fields=["run", "requested_fact"],
                        name="fervis_memory_art_req_idx",
                    ),
                    models.Index(
                        fields=["run", "fact_result"],
                        name="fervis_memory_art_result_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "memory_artifact_id"),
                        name="fervis_memory_art_run_id_uq",
                    )
                ],
            },
        ),
    ]
