# Generated by Django 5.2 on 2026-06-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fervis_lineage", "0006_memoryartifact"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelcall",
            name="model_subcalls_json",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
