# Generated by Django 5.2 on 2026-06-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fervis_lineage", "0008_alter_runtimeerrordetail_error_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogEndpoint",
            fields=[
                (
                    "catalog_endpoint_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                (
                    "catalog_endpoint_key",
                    models.CharField(max_length=128),
                ),
                ("endpoint_name", models.CharField(db_index=True, max_length=128)),
                (
                    "framework_kind",
                    models.CharField(max_length=64),
                ),
                (
                    "source_namespace_kind",
                    models.CharField(max_length=64),
                ),
                (
                    "source_namespace_path_json",
                    models.JSONField(blank=True, default=list),
                ),
                ("route_method", models.CharField(max_length=16)),
                ("route_path_template", models.CharField(max_length=512)),
                (
                    "route_name",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "api_schema_operation_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("handler_ref", models.CharField(max_length=512)),
                (
                    "domain_resource_names_json",
                    models.JSONField(blank=True, default=list),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_endpoints",
                        to="fervis_lineage.questionrun",
                    ),
                ),
            ],
            options={
                "db_table": "fervis_catalog_endpoint",
            },
        ),
        migrations.AddIndex(
            model_name="catalogendpoint",
            index=models.Index(
                fields=["framework_kind", "source_namespace_kind"],
                name="fervis_cat_endpoint_fw_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="catalogendpoint",
            index=models.Index(
                fields=["endpoint_name"],
                name="fervis_cat_endpoint_name_idx",
            ),
        ),
        migrations.AddField(
            model_name="sourceread",
            name="catalog_endpoint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="source_reads",
                to="fervis_lineage.catalogendpoint",
            ),
        ),
        migrations.RemoveIndex(
            model_name="sourceread",
            name="fervis_src_read_endpoint_idx",
        ),
        migrations.AddIndex(
            model_name="sourceread",
            index=models.Index(
                fields=["catalog_endpoint"],
                name="fervis_src_read_catalog_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="sourceread",
            name="endpoint_id",
        ),
        migrations.AddIndex(
            model_name="catalogendpoint",
            index=models.Index(
                fields=["run"],
                name="fervis_cat_endpoint_run_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogendpoint",
            constraint=models.UniqueConstraint(
                fields=["run", "catalog_endpoint_key"],
                name="fervis_cat_endpoint_run_key_uq",
            ),
        ),
    ]
