# Generated by Django 5.2 on 2026-06-21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fervis_lineage", "0009_catalog_endpoint_source_read_fk"),
    ]

    operations = []
