# Generated by Django 5.2 on 2026-06-21 15:25

from django.db import migrations, models

_SOURCE_READ_CATALOG_ENDPOINT_SAME_RUN_SQL = """
ALTER TABLE fervis_source_read
ADD CONSTRAINT fervis_src_read_catalog_same_run_fk
FOREIGN KEY (run_id, catalog_endpoint_id)
REFERENCES fervis_catalog_endpoint (run_id, catalog_endpoint_id)
DEFERRABLE INITIALLY DEFERRED
"""

_DROP_SOURCE_READ_CATALOG_ENDPOINT_SAME_RUN_SQL = """
ALTER TABLE fervis_source_read
DROP CONSTRAINT IF EXISTS fervis_src_read_catalog_same_run_fk
"""


class Migration(migrations.Migration):

    dependencies = [
        ("fervis_lineage", "0010_run_scoped_catalog_endpoints"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="catalogendpoint",
            constraint=models.UniqueConstraint(
                fields=("run", "catalog_endpoint_id"),
                name="fervis_cat_endpoint_run_id_uq",
            ),
        ),
        migrations.RunSQL(
            sql=_SOURCE_READ_CATALOG_ENDPOINT_SAME_RUN_SQL,
            reverse_sql=_DROP_SOURCE_READ_CATALOG_ENDPOINT_SAME_RUN_SQL,
        ),
    ]
