# Generated by Django 5.2 on 2026-06-26 11:17

import fervis.lineage.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fervis_lineage", "0011_catalog_endpoint_source_read_same_run"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="read_context_ref",
            field=models.JSONField(
                default=fervis.lineage.models.default_conversation_read_context_ref
            ),
        ),
    ]
