# Generated by Fervis on 2026-07-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fervis_lineage", "0012_conversation_read_context_ref"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="clarificationrequest",
            name="fervis_clar_req_basis_idx",
        ),
        migrations.AddField(
            model_name="clarificationrequest",
            name="need",
            field=models.CharField(
                choices=[
                    ("target_reference", "target_reference"),
                    ("answer_metric", "answer_metric"),
                    ("comparison_baseline", "comparison_baseline"),
                    ("catalog_input", "catalog_input"),
                    ("question_interpretation", "question_interpretation"),
                ],
                default="target_reference",
                max_length=64,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clarificationrequest",
            name="reason",
            field=models.CharField(
                choices=[
                    ("unresolved_reference", "unresolved_reference"),
                    ("multiple_matching_entities", "multiple_matching_entities"),
                    ("unsupported_reference", "unsupported_reference"),
                    ("missing_answer_metric", "missing_answer_metric"),
                    ("missing_comparison_baseline", "missing_comparison_baseline"),
                    ("missing_required_value", "missing_required_value"),
                    ("catalog_requires_choice", "catalog_requires_choice"),
                    ("ambiguous_interpretation", "ambiguous_interpretation"),
                ],
                default="unresolved_reference",
                max_length=64,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clarificationrequest",
            name="payload_json",
            field=models.JSONField(default=dict),
        ),
        migrations.RemoveField(
            model_name="clarificationrequest",
            name="basis",
        ),
        migrations.RemoveField(
            model_name="clarificationrequest",
            name="question_text",
        ),
        migrations.RemoveField(
            model_name="clarificationrequest",
            name="options_json",
        ),
        migrations.RemoveField(
            model_name="clarificationrequest",
            name="evidence_refs_json",
        ),
        migrations.AddIndex(
            model_name="clarificationrequest",
            index=models.Index(
                fields=["run", "need"], name="fervis_clar_req_need_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clarificationrequest",
            index=models.Index(
                fields=["run", "reason"], name="fervis_clar_req_reason_idx"
            ),
        ),
    ]
